import type { Metadata } from "next";
import "./globals.css";
import Navbar from '@/app/_components/Navbar/Navbar';
import Header from "@/app/_components/Header/Header";
import styles from './layout.module.scss';

// TODO: meta情報を適切に設定する
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <div className={styles.container}>
          <Navbar />
          <div className={styles.mainContent}>
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
